### ISSUE TITLE
getaddrino ENOTFOUND api.digitalparticle.com

### ISSUE THREAD

**Issue by eetee** [spywhere/vscode-guides#10]
Hi,

I'm investigating a performance issue that's quite similar to #6 input lag for typing. When I open the dev tools I'm seeing lots of these errors:
![image](https://cloud.githubusercontent.com/assets/3005702/18658529/00aade8e-7f58-11e6-8302-5d8d52329cb3.png)

I have no issue with sending usage stats, but will turn this off until it's corrected.

Thanks,
Eugene

**Comment by spywhere** [comment]
Currently, the server side of this stats system is down (I planned to change its structure, which would take a long time) so there is no problem turning it off at this moment. However, as you stated, I intend to change this behavior by increase it delay time by double it up every tries. This way the usage stats should not spamming the console as much as currently it is.

Thanks for filing the issue by the way, without this I wouldn't know that this could impact the performance of the extension.

**Comment by eetee** [comment]
No worries. I just wanted to be clear - I found this _while_ investigating a performance issue - not saying this is causing the performance issues 😃

**Comment by spywhere** [comment]
So, turning it off doesn't help solve the issue, does it?

**Comment by eetee** [comment]
Correct, turning it off does not solve the performance issues I am having.

**Comment by spywhere** [comment]
This issue has been solved on v0.5.1
