### ISSUE TITLE
Disappear lines

### ISSUE THREAD

**Issue by Aryman1983** [spywhere/vscode-guides#11]
Hi,
in new VC 1.5.3 after open editor lines show up in js file. Any action in the editor makes it disappear and never show up. 

Paul.

**Comment by spywhere** [comment]
What do you mean by "Any action in the editor makes it disappear and never show up"? Is it something you want to temporary disable the guide lines?

**Comment by Aryman1983** [comment]
When I click on editor area, or put cursor another line, all guide lines on the file is disappear.
Maybe this issue is related to VirtualBox?

**Comment by spywhere** [comment]
That could be the case, but could you try it on your host machine (your physical one)? There are some issues about graphics when run VSCode on VM, even on my own use.

**Comment by Aryman1983** [comment]
Hi,
in my host machine(Win 10) this issue doesn't exist. In VB graphics is emulated and propably VSC may be problem in rendering editor area :( 
Thanks for reply :)
Best regards :)
Paul.
