### ISSUE TITLE
Language-Specific Guides

### ISSUE THREAD

**Issue by ericoloewe** [spywhere/vscode-guides#13]
if i don't like guides in some language type (like js), currently i can't configure that i don't like to see guides in the same.

**Comment by spywhere** [comment]
Thanks! That indeed is a good idea to add to the extension. I'll let you know once I got the version published.

**Comment by spywhere** [comment]
The language-specific configuration has been added in v0.6.0. Please take a look at how to configure the settings in the [README](https://github.com/spywhere/vscode-guides) file.

**Comment by ericoloewe** [comment]
nice, thanks for that :)
