### ISSUE TITLE
New line dissapears

### ISSUE THREAD

**Issue by rhernandog** [spywhere/vscode-guides#14]
Hi,

I'm somehow a sucker for leaving white space on my code, mainly blank lines in my code to make it easier to read and follow. The thing is that those new lines are not highlighted. Something like this:
``` javascript
function myFunc(){

|  // some code here then a blank line

|  var a = 0:
|  var b = 1;

|  return a+b;

}
```
Happens in all file extensions I've checked so far, but the normal behaviour from vs code actually renders those blank lines correctly. Like this:
``` javascript
function myFunc(){
|
|  // some code here then a blank line
|
|  var a = 0:
|  var b = 1;
|
|  return a+b;
|
}
```

**Comment by spywhere** [comment]
That's expectable. Please see #1 and also FAQs on the README for more information.
