### ISSUE TITLE
Brackets projection on gutter

### ISSUE THREAD

**Issue by ArkhipovK** [spywhere/vscode-guides#15]
It's much easier to notice the brackets area, while there is a projection on gutter. Here some exaples how it might look like.

![2ff6a12e-dd8f-11e6-9624-d6f7b54d0337 1](https://cloud.githubusercontent.com/assets/9945452/23447481/1cf92066-fe6d-11e6-86d5-63587d86c7bc.gif)

or

![47924d34-c10a-11e6-909a-8c31fed90919 1](https://cloud.githubusercontent.com/assets/9945452/23447505/432adacc-fe6d-11e6-9e58-84a0eb784446.jpg)

**Comment by spywhere** [comment]
This feature has been implemented in v0.7.0 via `guides.active.gutter` configuration key.
