### ISSUE TITLE
Feature Request: Make Position of Line Customizable

### ISSUE THREAD

**Issue by dani-sc** [spywhere/vscode-guides#17]
It would be nice if the position of the currently active line (or all lines for that matter, but I don't use the other ones) could be customized. Currently, the line is always drawn on the left side of the spaces / tab. I'd really like to have it displayed on the right side instead, as seen in the middle of this image:
![image](https://cloud.githubusercontent.com/assets/11016034/26804869/cca4ede2-4a49-11e7-8cc3-b2d3a493c57c.png)

**Comment by spywhere** [comment]
Do you mean this?

![screen shot 2560-06-06 at 09 57 23](https://cloud.githubusercontent.com/assets/1087399/26811870/9330b3d4-4a9e-11e7-9196-489fc8132508.png)

Guides already supports active indentation on brackets by default.

**Comment by dani-sc** [comment]
No, I didn't mean in connection with brackets. It has nothing to do with brackets.

If you click in a line, you see the "active line" (in my screenshots below in orange) on the left. Currently, that "active line" is on the left side of the spaces/tabs. However, I would really like the option to position them on the right side of the spaces/tabs, if that's possible.

![active line position](https://user-images.githubusercontent.com/11016034/26946971-4f05e400-4c91-11e7-8bfb-1e4f6c3f819f.png)

**Comment by spywhere** [comment]
Ah, I got it. I'll take a look into it and keep you dated.

**Comment by spywhere** [comment]
This feature has been implemented in Guides v0.8.0
