### ISSUE TITLE
Active gutter icon cut off

### ISSUE THREAD

**Issue by alexbet** [spywhere/vscode-guides#22]
- Guides Version: 0.8.3
- VSCode Version: 1.13.1
- OS Version: Mac OS 10.12.5

As you can see below the active gutter icon that points left is cut off. Can you please fix this? Thanks!

<img width="323" alt="counter_js_ _autostradaforum_com" src="https://user-images.githubusercontent.com/3966760/27669596-959939b6-5c55-11e7-9266-cf15e144efd5.png">

**Comment by spywhere** [comment]
Do you have any problem with another gutter-related extensions? Could you try it as this extension does not set any position-related options to the gutter?

**Comment by alexbet** [comment]
I don't see any other problems, it is just this one, and just that icon in your extension. Do you have an extension to suggest that I can try?

**Comment by spywhere** [comment]
Hmm, could you try [this one](https://marketplace.visualstudio.com/items?itemName=extr0py.vscode-relative-line-numbers)?

**Comment by alexbet** [comment]
It works fine, see here:

<img width="361" alt="counter_js_ _autostradaforum_com" src="https://user-images.githubusercontent.com/3966760/27690798-4e5ff6ba-5cb0-11e7-8cf1-5e8a50365336.png">

You can also see the icon from your extension in-between too.  Very weird!

**Comment by spywhere** [comment]
Thanks for the feedback. I'll take a look and let you know.

**Comment by spywhere** [comment]
The issue has been fixed in v0.8.4
