### ISSUE TITLE
Guide lines are not straight

### ISSUE THREAD

**Issue by silverpeng** [spywhere/vscode-guides#23]
<img width="140" alt="qq20170726-155007 2x" src="https://user-images.githubusercontent.com/25680922/28610809-426e3ae8-721c-11e7-8b8a-7df32440be9d.png">

**Comment by spywhere** [comment]
Could you give me a list of installed extensions? Have you try this with just Guides and VSCode?

**Comment by silverpeng** [comment]
I installed Guides vetur，My problem with the MAC system is that window is good

**Comment by silverpeng** [comment]
The problem is in the.Vue file

**Comment by silverpeng** [comment]
In.Vue under template, when content is very long, will appear

**Comment by spywhere** [comment]
The problem could be that another extension also set the decoration at the same place as Guides does. When this happen, if that decoration has set some sort of margin or offset it could push the guide lines away (as you can see). If possible, could you give me the sample code that reproduce the issue? Otherwise, this would be hard to tackle the problem as this is not a usual case.

**Comment by silverpeng** [comment]
`{
    "window.zoomLevel": 1,
    "workbench.iconTheme": "vscode-icons",
    "vsicons.projectDetection.autoReload": false,
    // "workbench.sideBar.location": "left",
    "editor.fontSize": 13,
    "guides.active.width": 1,
    "guides.stack.color.dark": [
    "rgba(252, 30, 112, .30)",
    "rgba(166, 226, 46, .30)",
    "rgba(96, 211, 232, .30)",
    "rgba(253, 151, 31, .30)"
    ],
    "guides.active.color.dark": [
    "rgba(252, 30, 112, .90)",
    "rgba(166, 226, 46, .90)",
    "rgba(96, 211, 232, .90)",
    "rgba(253, 151, 31, .90)"
    ],
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/dist": true
    },
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.DS_Store": true,
        "**/node_modules": true,
        "**/iOS": true
    },
    "colorize.languages": [
            "javascript",
            "css",
            "sass",
            "scss",
            "less",
            "pcss",
            "sss",
            "stylus",
            "xml",
            "svg"
    ],
    "emmet.syntaxProfiles": {
        "vue-html": "html",
        "vue": "html"
    },
    "editor.renderIndentGuides": false,
    "editor.tabSize": 4,
    "files.trimTrailingWhitespace": true,
    "editor.insertSpaces": true,
    "editor.formatOnSave": false,
    "files.associations": {
        "*.vue": "vue"
    },
    "eslint.autoFixOnSave": true,
    "eslint.options": {
        "extensions": [
            ".js",
            ".vue"
        ],
         "plugins": ["html"]
    },
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "vue",
        "vue-html"
    ],
    "extensions.autoUpdate": true,
    "editor.cursorBlinking": "smooth",
    "workbench.welcome.enabled": true,
    "guides.enabled": true,
    "workbench.colorTheme": "Material Neutral - Classic"
}`

**Comment by silverpeng** [comment]
This is my vscode settings

**Comment by spywhere** [comment]
Close due to inactivity from the issue author. Please create a new one with more information (including reference to this issue), if the issue still persist.
