### ISSUE TITLE
Determine guide color based on starting line content

### ISSUE THREAD

**Issue by W4RH4WK** [spywhere/vscode-guides#25]
This is a feature request which I think would fit this extension. Although it might go beyond the scope of it.
The idea comes from [Visual Studio's *Structure Visualizer* Extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.StructureVisualizer).

The extension for Visual Studio colors the indent guides differently based on the type of the block.
For instance, loops result in a red colored indent guide, while *if*s do have a green one:

![image](https://user-images.githubusercontent.com/328798/34471111-bad289f8-ef3f-11e7-8501-46042ea60746.png)

So, while I don't think there is currently no way to reliably determine whether a given block is a loop or a conditional, a filetype based regex could probably suffice. What do you think?

**Comment by spywhere** [comment]
A partial implementation of this feature would be [this issue](https://github.com/spywhere/vscode-guides/issues/16). Although it is very possible to implement, this feature might take a while to get it done as this would get involve with a performance impact from RegExp if not a language server.

**Comment by spywhere** [comment]
To reduce the complexity of implementation, I'll consider [this issue](https://github.com/spywhere/vscode-guides/issues/16) to partially solve this issue hence this issue is closed.
