### ISSUE TITLE
Setting "normal.enabled" to false still shows normal lines

### ISSUE THREAD

**Issue by vr8hub** [spywhere/vscode-guides#29]
- [x] I have search [open issues](https://github.com/spywhere/vscode-guides/issues) for duplicate issues
- [x] I have search [close issues](https://github.com/spywhere/vscode-guides/issues?q=is%3Aissue+is%3Aclosed) for potential fixes
- Guides Version: 0.9.1
- VSCode Version: 1.22.1
- OS Version: OSX 10.12.6

Steps to Reproduce:
I only want to see active lines, i.e. the lines on the block where my cursor is. I set these options in my user settings.

```
"guides.active.enabled": true,
"guides.normal.enabled": false,
"guides.overrideDefault": true,
```

Actual Behaviour:
I still get all of the lines.

Expected Behaviour:
I only expected to see the active lines when I was on a block. IOW, in this screen shot, I expected only the red "active" line to show. That is the behavior I am looking for. Are the above settings not how to accomplish it?

<img width="334" alt="vscode guides" src="https://user-images.githubusercontent.com/19378955/38745994-dc79df36-3f0b-11e8-949e-b97a0187e1b2.png">

**Comment by spywhere** [comment]
You have to also disable stack guide lines by setting `guides.stack.enabled` to `false`.
