### ISSUE TITLE
Extension(v0.2.2) fails to load on startup in vscode v1.0.1-insider (Win7)

### ISSUE THREAD

**Issue by andischerer** [spywhere/vscode-guides#3]
Hi There,

first of all :+1: for this extension. 

If i start vscode v1.0.1-insider the indent guides aren't visible anymore.
Here is the corresponding callstack:
![image](https://cloud.githubusercontent.com/assets/930604/14735272/4b66fa48-0870-11e6-81bf-17849fa0ca4b.png)

This is because `this.configurations.get` [here](https://github.com/spywhere/vscode-guides/blob/master/src/extension.ts#L106) and [here](https://github.com/spywhere/vscode-guides/blob/master/src/extension.ts#L419) returns undefined so the forEach loop fails.

I havent set any of the Guide settings in my custom user settings. I testwise added undefinded checks for `this.configurations.get` and the extension starts working again. Maybe there was an api change for `this.configurations.get` from the vscode folks.

Thanks again

**Comment by spywhere** [comment]
Could you check the settings file (not yours but the default one)? The only way that leads to this issue is the default settings are not set. `configurations.get` will use default settings when there is not option set in the user's settings file.

Anyway, I will add additional default to the code so this issue won't occur again.

**Comment by andischerer** [comment]
There is actually a guides section in the default settings:
```json
//-------- Guides Configurations --------

	// Indentation background colors.
	"guides.indent.backgrounds": [],

	// Hide indentation background in selections.
	"guides.indent.hideBackgroundOnSelection": true,

	// Show start-of-line indentation guides.
	"guides.indent.showFirstIndentGuides": true,

	// Normal indentation guides rendering width.
	"guides.normal.width": "1px",

	// Normal indentation guides rendering color.
	"guides.normal.color": "rgba(60, 60, 60, 0.75)",

	// Normal indentation guides rendering style.
	"guides.normal.style": "solid",

	// Hide normal indentation guides in selections.
	"guides.normal.hideOnSelection": true,

	// Enable active indentation guides in addition to normal indentation guides.
	"guides.active.enabled": true,

	// Active indentation guides rendering width.
	"guides.active.width": "1px",

	// Active indentation guides rendering color.
	"guides.active.color": "rgba(120, 60, 60, 0.75)",

	// Active indentation guides rendering style.
	"guides.active.style": "solid",

	// Hide active indentation guides in selections.
	"guides.active.hideOnSelection": true,

	// Ruler guide stop points.
	"guides.rulers": [],

	// Ruler guides rendering width.
	"guides.ruler.width": "1px",

	// Ruler guides rendering color.
	"guides.ruler.color": "#cc9999",

	// Ruler guides rendering style.
	"guides.ruler.style": "solid",

	// Hide ruler guides in selections.
	"guides.ruler.hideOnSelection": true,

	// Time duration between each guide lines update (in seconds).
	"guides.updateDelay": 0.1,

	// Override default Visual Studio Code behaviours (such as indentation guides or rulers).
	"guides.overrideDefault": false,
```

**Comment by andischerer** [comment]
I've debugged a little further. Seems like any extension specific settings couldn' be loaded in 1.0.1-insiders.
e.g
`vscode.workspace.getConfiguration("tslint")` returns an empty Object
while
`vscode.workspace.getConfiguration("editor")` returns all editor settings

I've downgraded to vscode 1.0 and everything was working fine again. So it looks like this is a bug in insiders build.

**Comment by spywhere** [comment]
Thanks, I also working on which extension has affect with this issue (so I can file an issue to vscode team). If you don't mind, can you share which extensions have affected so far?

**Comment by andischerer** [comment]
Extensions i've tested so far:
```
Guides
CoffeeLint
TSlint
Path Intellisense
```
Looks like every user installed extension couldnt load their settings. `workspace.getConfiguration('extension')` returns an empty object.

**Comment by spywhere** [comment]
Thanks. I will file the issue now :)

**Comment by andischerer** [comment]
Np.

btw i discovered a new default setting in insiders:
```json
	// Controls whether the editor should render indent guides
	"editor.indentGuides": false,
```
there is now a buildin support for indent guides in vscode. Although not as feature rich compared to your extension.

**Comment by spywhere** [comment]
Yup, that is expectable. They are working on built-in indent guide in this iteration for this month release.
