### ISSUE TITLE
Settings / Configurations description is unclear

### ISSUE THREAD

**Issue by jcklpe** [spywhere/vscode-guides#30]
Maybe this is more common dev knowledge than I have or something but I'm not entirely clear on the differences between active, stacked, and normal. Also, I don't seem to be seeing any real changes to my guides no matter what I do to my settings.

**Comment by spywhere** [comment]
Are [these](https://github.com/spywhere/vscode-guides#faqs) helps?

**Comment by jcklpe** [comment]
@spywhere Yes somewhat though a picture would also be helpful. I'm not seeing any of the indentions described in that FAQ and I'm not clear on why that is. Maybe it's that I have my settings wrong? Or maybe it's something else, I'm not clear, and being able to see a visual example of those guides would help. 

Also some of the other settings like hideOnSelection are not totally clear. I would assume that means that when you select a line, the guide hides, but isn't the "active" state the designation for what guide is selected?

**Comment by jcklpe** [comment]
Okay so I actually have them visible now, which is good. It seems that I have to completely restart vscode in order to see changes to my settings with it. 

Okay so I think this would be the way to put things:

Active is the section you have clicked within. 

Normal is everything under Active. 

Stacked is everything over active. Is that correct?

**Comment by jcklpe** [comment]
![image](https://user-images.githubusercontent.com/9451726/40244594-d82f5788-5a88-11e8-97f6-1d3f054a24a7.png)

**Comment by spywhere** [comment]
Hey, sorry for such a late response. Your feedback is really appreciated, I'm going to update the screenshot and included the image in the FAQ for future reference.

On the settings / configurations side, there is an explanation of each option if you're hovering your cursor over them, which is the expected behaviour through VSCode design though.

**Comment by jcklpe** [comment]
No problem and thank you for your patience. After getting the hang of it I've
got it set up just the way I want and it looks great! It's a really great
plugin!


Sincerely,David Aslan French  
Jackalope.tech Design X Code: Pushing the boundaries of design, art, and code.
 jackalope.tech  
Find me on Facebook  Let's connect!  








On Sat, May 19, 2018 11:45 PM, Sirisak Lueangsaksri notifications@github.com 
wrote:
Hey, sorry for such a late response. Your feedback is really appreciated, I'm
going to update the screenshot and included the image in the FAQ for future
reference.
