### ISSUE TITLE
Make gutter glyphs vector

### ISSUE THREAD

**Issue by everdrone** [spywhere/vscode-guides#31]
- [x] I have search [open issues](https://github.com/spywhere/vscode-guides/issues) for duplicate issues
- [x] I have search [close issues](https://github.com/spywhere/vscode-guides/issues?q=is%3Aissue+is%3Aclosed) for potential fixes
- Guides Version: 0.9.1
- VSCode Version: 1.24.1
- OS Version: macOS High Sierra 10.13.5

Steps to Reproduce:

1. open VSCode
2. zoom in

Actual Behaviour:
closing and opening [*gutter* brackets](https://github.com/spywhere/vscode-guides/tree/develop/images/gutters) appear blurry

Expected Behaviour:
pixel sharp vector indicators

**Comment by spywhere** [comment]
This has been the issue before but in reverse. The first time I add this feature, the pixel is sharp on the retina display and such, but becomes too big on regular screen. I'll take a look if VSCode has supports a vector graphic and fix this accordingly.

**Comment by everdrone** [comment]
VSCode should support vector graphics, there is an extension called [Bookmarks](https://github.com/alefragnani/vscode-bookmarks) that implemented vector [gutter indicators](https://github.com/alefragnani/vscode-bookmarks/blob/master/images/bookmark.svg) a while ago

I already tried to mimic the open/closed gutter indicators both in dark and light mode, but maybe you have the source for the files and can do a better job

here:
[gutter-svg.zip](https://github.com/spywhere/vscode-guides/files/2107726/gutter-svg.zip)

**Comment by spywhere** [comment]
I'll let you know once the fix is up.

**Comment by spywhere** [comment]
An update has been published.

**Comment by everdrone** [comment]
Thanks! looks super nice!

![wow](https://user-images.githubusercontent.com/22671061/41498290-0321d7ac-716a-11e8-9e38-e097bc685633.png)
