### ISSUE TITLE
display 'only active line' as example in README.md

### ISSUE THREAD

**Issue by ax1** [spywhere/vscode-guides#32]
- Guides Version:0.9.2
- VSCode Version:1.29.1

For some people, displaying *all* the vertical lines is ugly, but displaying only the active line is really helpful.

Instead of having to implement a new feature (and maintain code later, bugs, vscode changes,  and so on...), this feature can be achieved with the current settings easily.

If you feel that it could be useful for people, adding the settings example in the readme (or a gif file) should be enough. If not interesting, just close the issue, no problem, I'll document it in personal storage because to me it is really nice.

settings.json in vscode:

```json
{
  "guides.active.color.dark": "rgba(100, 100, 100, 0.5)",
  "guides.normal.enabled": false,
  "guides.stack.enabled": false,
}
```
Example:

![vscode-gides_1line](https://user-images.githubusercontent.com/16510021/49329004-7e15b580-f579-11e8-9a05-607089f5f043.gif)

**Comment by spywhere** [comment]
Thanks for the suggestion, however, I think this would be great to list as a community suggestions instead. I'll close the issue, and if there are enough suggestions, I might make a new section just for this, or better, create a new feature where user can download / try some community settings. :)

**Comment by aleclarson** [comment]
Thank you @ax1
