### ISSUE TITLE
[Renewal] Guides skip blank lines

### ISSUE THREAD

**Issue by kanlukasz** [spywhere/vscode-guides#36]
Hello

I know about previous ticket ( https://github.com/spywhere/vscode-guides/issues/1 ) but it was quite a long time ago, so I would like to ask if something has changed?

Is it now possible to fix it and show indent on empty lines?

**Comment by spywhere** [comment]
Nope, VSCode team still not shipped with enough API to make this come true.

**Comment by kruzyk** [comment]
Is there any hope to make it happen?
