### ISSUE TITLE
Is extension deprecated?

### ISSUE THREAD

**Issue by Ivajkin** [spywhere/vscode-guides#44]
- [x] I have search [open issues](https://github.com/spywhere/vscode-guides/issues) for duplicate issues
- [x] I have search [close issues](https://github.com/spywhere/vscode-guides/issues?q=is%3Aissue+is%3Aclosed) for potential fixes
- Guides Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install extension 
2. Get warning message

Actual Behaviour:
"Guides extension has detected that you are using "editor.renderIndentGuides" settings. Guides will now disable all indentation guides by override the style to "none"."

Expected Behaviour:
Work properly after you install extension

**Comment by spywhere** [comment]
May be you might want to check [this out](https://github.com/spywhere/vscode-guides/tree/master#how-guides-different-from-built-in-indentation-guides)?
