### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by atrodot** [spywhere/vscode-guides#45]
- Issue Type: `Performance`
- Extension Name: `guides`
- Extension Version: `0.9.3`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.39.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/ehsan/spywhere.guides-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by spywhere** [comment]
Please post more info
