### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by AlimusSifar** [spywhere/vscode-guides#53]
[spywhere.guides-unresponsive.cpuprofile.txt](https://github.com/spywhere/vscode-guides/files/6168950/spywhere.guides-unresponsive.cpuprofile.txt)
- Issue Type: `Bug`
- Extension Name: `guides`
- Extension Version: `0.9.3`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by spywhere** [comment]
Please post more info.
