### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sagar5690** [spywhere/vscode-guides#61]
- Issue Type: `Performance`
- Extension Name: `guides`
- Extension Version: `0.9.3`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/sagarbarot/spywhere.guides-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by spywhere** [comment]
Please post more info.
