### ISSUE TITLE
Guidelines don't get rendered after scrolling

### ISSUE THREAD

**Issue by seahindeniz** [spywhere/vscode-guides#67]
- [x] I have search [open issues](https://github.com/spywhere/vscode-guides/issues) for duplicate issues
- [x] I have search [close issues](https://github.com/spywhere/vscode-guides/issues?q=is%3Aissue+is%3Aclosed) for potential fixes
- Guides Version: 0.9.3
- VSCode Version: 1.63.2
- OS Version: Darwin arm64 21.2.0

Steps to Reproduce:

1. Open a new file that has ~1000 lines
2. Scroll down (or up) to line 500-ish
3. Observe the rendering issue

The only way to trigger re-render lines is to click somewhere in the file

Actual Behaviour:
![image](https://user-images.githubusercontent.com/5789670/148029253-5d044fb1-a02b-4a44-baa9-4a3cc52e4b72.png)

Expected Behaviour:
![image](https://user-images.githubusercontent.com/5789670/148029279-837a6884-3e81-48e5-adb7-2ba236ae352b.png)

**Comment by spywhere** [comment]
That's the expected behavior. You could adjust the behavior and its limit through the following options

- `guides.limit.mode`
- `guides.limit.maximum`
