### ISSUE TITLE
Make active guide highlight according to the cursor position

### ISSUE THREAD

**Issue by Elarcis** [spywhere/vscode-guides#7]
The extension always highlights the containing block of the line you're on.

But when the caret is right after the opening or right before the closing of an instruction block (brackets, parenthesis, etc.), I think it should consider being "inside" of the instruction block, thus highlighting the next indentation level instead.

This could also apply to multiline function calls, array declarations, etc. to easily find the boundaries of these.

The current behavior:
![wrong](https://cloud.githubusercontent.com/assets/990841/16044642/97bb02e6-3245-11e6-89e4-52b83f36ca1b.png)

The guide that should be highlighted instead:
![right](https://cloud.githubusercontent.com/assets/990841/16044646/9dd2d294-3245-11e6-8a08-1791c5575e51.png)

Does this sound logical, and is it feasible ?

**Comment by spywhere** [comment]
Hmm... Sound logical? Yes. Feasible? May be...

For the example you gave, I think it would make more sense to be that way because `files.exclude` part is in another scope of its member hence the active guide should be highlighted the indentation level of that `files.exclude` scope.

Guides does not use cursor position to calculate the active guides. It use current line as a base to calculate for the rest of the active guides (on the rest of the document).

I will mark this as an enhancement instead since this is not a crash-related or miscalculation issue.

**Comment by Elarcis** [comment]
It's perfectly clear, thanks !

I didn't realize right away, but I based my reasoning on Notepad++. It seems they're "simply" highlighting the guide the matching brace is placedon. If it's offset by a few spaces, it highlights nothing.

You seem to know VSCode's API way better than me, I'll let you decide if you implement it, and what's best from your point of view :D

**Comment by spywhere** [comment]
I based my implementation from Sublime Text. Here...

![stactiveguide](https://cloud.githubusercontent.com/assets/1087399/16047969/71a08f90-327c-11e6-8bb1-db77f90fe7a5.gif)

I might implement this after the VSCode team implement a "visible lines" API (I guess this would take a long time for them) which will improve the Guides performance a lot.

**Comment by ArkhipovK** [comment]
Here some exaples how it might look like

![2ff6a12e-dd8f-11e6-9624-d6f7b54d0337 1](https://cloud.githubusercontent.com/assets/9945452/23447481/1cf92066-fe6d-11e6-86d5-63587d86c7bc.gif)

or

![47924d34-c10a-11e6-909a-8c31fed90919 1](https://cloud.githubusercontent.com/assets/9945452/23447505/432adacc-fe6d-11e6-9e58-84a0eb784446.jpg)

**Comment by spywhere** [comment]
@ArkhipovK Could you please file another issue for the gutter feature? I think that's really neat though, might take a look on that one.

**Comment by ArkhipovK** [comment]
Not a problem.

**Comment by spywhere** [comment]
This feature has been implemented in v0.7.0.
