### ISSUE TITLE
Wrong Line highlighted

### ISSUE THREAD

**Issue by daslicht** [spywhere/vscode-guides#8]
Hi,
when I clicked a node (the nav in the image beneath) the line of its parent is highlighted, 
should't be the line highlighted of the clicked div ?
![](http://i.imgur.com/m51ryUi.png)

**Comment by spywhere** [comment]
That's the way I implement it (I reference it from Sublime Text). Take a look [here](https://github.com/spywhere/vscode-guides/issues/7), it might help understand this better.

**Comment by daslicht** [comment]
Got it, it makes totally sense, that way we don't even have to find the closing tag
