### ISSUE TITLE
Editor guidelines

### ISSUE THREAD

**Issue by Boggin** [spywhere/vscode-guides#9]
This may not be something you want to do but I'd like to suggest it.

I like to have guidelines at character columns 79 and 120 to help me organise the line-lengths of my code.

Is this something that Guides could add? Or is it already covered by another VSCode plug-in?

For example, in Visual Studio I use “Editor Guidelines” [https://visualstudiogallery.msdn.microsoft.com/da227a0b-0e31-4a11-8f6b-3a149cf2e459].

**Comment by spywhere** [comment]
TL;DR; Use VSCode configuration key `editor.rulers` to show your preferred guide lines

Guides used to have this feature in the past. But after VSCode already [implemented](https://github.com/Microsoft/vscode/issues/1673) it, I recommended you to use those instead.
